* maps/five.txt:  New file. * maps/one.txt:  updated and enhanced. * maps/simple.txt:  updated and enhanced. * maps/two.txt:  updated and enhanced. * python/pen2map.py:  many bugfixes applied. * python/tiny.map:  rebuilt. * python/tiny.pen:  rebuilt. * python/txt2map:  minor changes. * python/txt2pen.py:  many bugfixes applied.

diff --git a/python/txt2map b/python/txt2map
--- a/python/txt2map
+++ b/python/txt2map
@@ -2,16 +2,15 @@
 
 echo -n "txt2pen: "
 if python txt2pen.py -o tiny.pen $1 ; then
-   echo "pass"
+    echo "pass"
 else
-   echo "failed"
-   exit 1
+    echo "failed"
+    exit 1
 fi
 
-echo -n "pen2map: "
 if python pen2map.py -s -e -o tiny.map tiny.pen ; then
-   echo "pass"
+    echo "pen2map: pass"
 else
-   echo "failed"
-   exit 1
+    echo "pen2map: failed"
+    exit 1
 fi
